# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# variable "region" {
#   description = "AWS region"
#   default     = "us-west-1"
# }

# variable "instance_type" {
#   description = "Type of EC2 instance to provision"
#   default     = "t2.micro"
# }

# variable "instance_name" {
#   description = "EC2 instance name"
#   default     = "Provisioned by Terraform"
# }

variable "zone_id" {
  description = "Cloudflare zone ID"
  type        = string
  default     = "5962c212dcd3ecee048bfc57ecbdeec7"
}

variable "name" {
  description = "Name of the DNS record"
  type        = string
  default     = "chert-ter.mzdan.live"
}

variable "content" {
  description = "Content of the DNS record"
  type        = string
  default = "10.163.91.34"
}

variable "comment" {
  description = "Value of the comment for the DNS record"
  type        = string
  default = "chert record generated by terraform"
}
